---
- name: Download Mysql 8.0.43 RPMs
  get_url:
    url: "https://dev.mysql.com/get/mysql-8.0.43-1.el8.x86_64.rpm-bundle.tar"
    validate_certs: false
    dest: /tmp/
    mode: '0644'
  when: mysql_version == "8.0.43" and ansible_os_family == "RedHat" or ansible_os_family == "Rocky" and ansible_os_version == "8"

- name: Download Mysql 8.0.43 RPMs
  get_url:
    url: "https://dev.mysql.com/get/mysql-8.0.43-1.el9.x86_64.rpm-bundle.tar"
    validate_certs: false
    dest: /tmp/
    mode: '0644'
  when: mysql_version == "8.0.43" and ansible_os_family == "RedHat" or ansible_os_family == "Rocky" and ansible_os_version == "9"

- name: Download Mysql 8.0.43 RPMs
  get_url:
    url: "https://dev.mysql.com/get/mysql-8.0.43-1.el10.x86_64.rpm-bundle.tar"
    validate_certs: false
    dest: /tmp/
    mode: '0644'
  when: mysql_version == "8.0.43" and ansible_os_family == "RedHat" or ansible_os_family == "Rocky" and ansible_os_version == "10"

- name: Extract Mysql 8.0.43 RPMs
  command: tar -xvf /tmp/mysql-8.0.43-1.el8.x86_64.rpm-bundle.tar -C /tmp/
  when: mysql_version == "8.0.43" and ansible_os_family == "RedHat" or ansible_os_family == "Rocky" and ansible_os_version == "8"

- name: Extract Mysql 8.0.43 RPMs
  command: tar -xvf /tmp/mysql-8.0.43-1.el9.x86_64.rpm-bundle.tar -C /tmp/
  when: mysql_version == "8.0.43" and ansible_os_family == "RedHat" or ansible_os_family == "Rocky" and ansible_os_version == "9"

- name: Extract Mysql 8.0.43 RPMs
  command: tar -xvf /tmp/mysql-8.0.43-1.el10.x86_64.rpm-bundle.tar -C /tmp/
  when: mysql_version == "8.0.43" and ansible_os_family == "RedHat" or ansible_os_family == "Rocky" and ansible_os_version == "10"

